WebApplication1/WebApplication1/Controllers/BasliıkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class BaslikController : Controller
    {
        DataClasses1DataContext db = new DataClasses1DataContext();

        public ActionResult Basliklar()
        {
            BasliklarSayfasiModel model = new BasliklarSayfasiModel();
            if (Session["Giris"] == null)
            {
                // Giriş yapılmadıysa.
                model.Id = "0";
                model.Kullanici = "";
            }
            else
            {
                // Session dolu geliyor.
                // İçindeki dataları alıyorum.
                String[] girisbilgileri = Session["Giris"] as string[];
                model.Id = girisbilgileri[0];
                model.Kullanici = girisbilgileri[1];
            }

            model.Basliklar = (from x in db.tbl_basliks
                               where x.Onay == true
                               orderby x.EklenmeTarihi descending
                               select new BaslikModel
                               {
                                   Baslik = x.Isim,
                                   Id = x.Id,
                                   MesajSayisi = x.tbl_mesajs.Count,
                                   Kullanici = x.tbl_kullanici.Isim + " " + x.tbl_kullanici.Soyisim,
                                   Tarihi = x.EklenmeTarihi
                               }).ToList();
            return View(model);
        }



        [HttpGet]
        public ActionResult YeniBaslikEkle()
        {
            YeniBaslikEklemeModel yenimodel = new YeniBaslikEklemeModel();
            DataClasses1DataContext db = new DataClasses1DataContext();

            yenimodel.Kategoriler = (from x in db.tbl_kategoris
                                     where x.Aktif == true
                                     orderby x.Isim ascending
                                     select x).ToList();

            return View(yenimodel);
        }


        [HttpPost]
        public ActionResult YeniBaslikEkle(YeniBaslikEklemeModel gelenmodel)
        {
            DataClasses1DataContext db = new DataClasses1DataContext();

            YeniBaslikEklemeModel sonucmodel = new YeniBaslikEklemeModel();

            sonucmodel.Kategoriler = (from x in db.tbl_kategoris
                                     where x.Aktif == true
                                     orderby x.Isim ascending
                                     select x).ToList();


            if (Session["Giris"] != null)
            {
                String[] girisbilgileri = Session["Giris"] as string[];
                int UserId = Convert.ToInt32(girisbilgileri[0]);

                tbl_baslik yenibaslik = new tbl_baslik();
                yenibaslik.EklenmeTarihi = DateTime.Now;
                yenibaslik.Isim = gelenmodel.Isim;
                yenibaslik.KategoriId = gelenmodel.KategoriID;
                yenibaslik.KullaniciId = UserId;
                yenibaslik.Onay = false;

                db.tbl_basliks.InsertOnSubmit(yenibaslik);
                db.SubmitChanges();

                sonucmodel.Error = "Başlık başarıyla eklendi. Lütfen Admin'in onayı için bekleyiniz.";
            }
            else
            {
                sonucmodel.Error = "Lütfen İlk önce Siteye giriş yapınız.";
            }
           

            return View(sonucmodel);
        }
    }
}

WebApplication1/WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        DataClasses1DataContext db = new DataClasses1DataContext();

        public ActionResult Index()
        {
            HomeModel model = new HomeModel();
            if (Session["Giris"] == null)
            {
                // Giriş yapılmadıysa.
                model.Id = "0";
                model.Kullanici = "";
            }
            else
            {
                // Session dolu geliyor.
                // İçindeki dataları alıyorum.
                String[] girisbilgileri = Session["Giris"] as string[];
                model.Id = girisbilgileri[0];
                model.Kullanici = girisbilgileri[1];
            }

            model.Basliklar = (from x in db.tbl_basliks
                               where x.Onay == true
                               orderby x.EklenmeTarihi descending
                               select new BaslikModel
                               {
                                   Baslik = x.Isim,
                                   Id = x.Id,
                                   MesajSayisi = x.tbl_mesajs.Count,
                                   Kullanici = x.tbl_kullanici.Isim + " " + x.tbl_kullanici.Soyisim,
                                   Tarihi = x.EklenmeTarihi
                               }).Take(20).ToList();

            model.Mesajlar = (from x in db.tbl_mesajs
                              orderby x.EklenmeTarihi descending
                              select new MesajModel
                              {
                                  Mesaj = x.MesajYazısı,
                                  Id = x.Id,
                                  Baslik = x.tbl_baslik.Isim,
                                  Kullanici = x.tbl_kullanici.Isim + " " + x.tbl_kullanici.Soyisim,
                                  Tarih = x.EklenmeTarihi
                              }).Take(20).ToList();

            model.Kategoriler = (from x in db.tbl_kategoris
                                 where x.Aktif == true
                                 select new KategoriModel
                                 {
                                     KategoriAdi = x.Isim,
                                     Id = x.Id,
                                     BaslikSayisi = x.tbl_basliks.Count
                                 }).ToList();

            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Hakkimizda()
        {
            HakkimizdaModel model = new HakkimizdaModel();
            return View(model);
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication1/WebApplication1/Views/Home/Hakkimizda.cshtml
@model WebApplication1.Models.HakkimizdaModel

@{
    ViewBag.Title = "Hakkimizda";
}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive admin dashboard and web application ui kit. ">
    <meta name="keywords" content="login, signin">
    <title>Login Page 1 &mdash; TheAdmin</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,300i" rel="stylesheet">
    <!-- Styles -->
    <link href="~/css/core.min.css" rel="stylesheet">
    <link href="~/css/app.min.css" rel="stylesheet">
    <link href="~/css/style.min.css" rel="stylesheet">
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="~/img/apple-touch-icon.png">
    <link rel="icon" href="~/img/favicon.png">
</head>
<body style="background: url(../img/wallpaper.jpg) no-repeat center center fixed; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;">
    <div class="row min-h-fullscreen center-vh p-20 m-0">
        <div class="col-12">
            <div class="card card-shadowed px-50 py-30 w-400px mx-auto" style="max-width: 100%">
                <center><h5 class="text-uppercase">Hakkımızda</h5></center>
                <center><img src="~/img/mediforumlogo.png" style="width:256px;height:auto;" /></center>
                <br>
                <h5><center>Bütün Öğrencilerin tek bir çatı altında toplanıp hep birlikte SOHBET, MUHABBET edip yeni dostluklar başlatıp, yeri geldiğinde birbirleriyle yardımlaşabilmeleri için kurduğumuz bir platformdur.</center></h5>
            </div>
        </div>
    </div>


    <!-- Scripts -->
    <script src="~/js/core.min.js"></script>
    <script src="~/js/app.min.js"></script>
</body>
</html>

WebApplication1/WebApplication1/Views/Home/Index.cshtml
@model WebApplication1.Models.HomeModel
@{
    ViewBag.Title = "Home Page";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive admin dashboard and web application ui kit. Pre designed block of data to use in your web app.">
    <meta name="keywords" content="widget, list, table, comments, popular, recent">
    <title>List Widgets &mdash; TheAdmin</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,300i" rel="stylesheet">
    <!-- Styles -->
    <link href="css/core.min.css" rel="stylesheet">
    <link href="css/app.min.css" rel="stylesheet">
    <link href="css/style.min.css" rel="stylesheet">
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="../assets/img/apple-touch-icon.png">
    <link rel="icon" href="../assets/img/favicon.png">
</head>
<body>
    <!-- Preloader -->
    <div class="preloader">
        <div class="spinner-dots">
            <span class="dot1"></span>
            <span class="dot2"></span>
            <span class="dot3"></span>
        </div>
    </div>

    <!-- Sidebar -->
    <!-- END Sidebar -->
    <!-- Topbar -->
    <header class="topbar">

        <div class="topbar-left">
            <header class="sidebar-header">
                <a class="logo-icon" href="../index.html"><img src="img/logo-icon-light.png" alt="logo icon"></a>
                <span class="logo">
                    <a href="../index.html"><img src="img/logo-light.png" alt="logo"></a>
                </span>
            </header>

            <div class="topbar-divider d-none d-md-block"></div>
            <nav>
                <a style="padding-left:5px;padding-right:5px;" href="/html/">Ana Sayfa</a> |
                <a style="padding-left:5px;padding-right:5px;" href="/js/">İletişim</a> |
                <a style="padding-left:5px;padding-right:5px;" href="@Url.Action("Hakkimizda", "Home")">Hakkımızda</a>
            </nav>

        </div>
        @if (String.IsNullOrEmpty(Model.Kullanici))
        {
            <div class="topbar-right">
                <a style="padding-left:5px;padding-right:5px;" class="float-right" href="@Url.Action("Login","Account")">Giriş Yap</a>
                <a style="padding-left:5px;padding-right:5px;" class="float-right" href="@Url.Action("Register","Account")">Üye Ol</a>
            </div>
        }
        else
        {
            <div class="topbar-right">
                <a style="padding-left:5px;padding-right:5px;" class="float-right" href="@Url.Action("Login","Account")">Hoşgeldiniz @Model.Kullanici</a>
            </div>
        }

    </header>
    <!-- END Topbar -->
    <!-- Main container -->
    <main class="main-container">
        <div class="main-content">
            <div class="row">
                <div class="col-md-5">
                    <div class="card">
                        <h5 class="card-title"><strong>En Yeni Başlıklar</strong></h5>
                        <div class="media-list media-list-hover media-list-divided">
                            @foreach(var item in Model.Basliklar)
                            {
                                <a class="media media-single" href="#">
                                <img class="w-40px" src="img/letter.png">
                                <div class="media-body">
                                    <h6>@item.Baslik (@item.Tarihi, <strong style="font-weight:500;">@item.MesajSayisi Adet</strong> Mesaj)</h6>
                                    <small class="text-fader">@item.Kullanici</small>
                                </div>
                            </a>
                            }
                        </div>
                    </div>
                    <div style="width:100%;">
                        <a href="@Url.Action("Basliklar","Baslik")" target="_self" style="float:right; background-color:lightblue;padding:5px;color:black;font-size:14px;">Tüm Başlıklar</a>
                    </div>
                </div>

                <div class="col-md-3 col-lg-3">
                    <div class="card">
                        <h5 class="card-title"><strong>Kategoriler</strong></h5>
                        <div class="media-list media-list-hover media-list-divided">
                            @foreach (var item in Model.Kategoriler)
                            {
                                <a class="media media-single" href="#">
                                    <span class="title">@item.KategoriAdi</span>
                                    <span class="badge badge-pill badge-secondary">@item.BaslikSayisi</span>
                                </a>
                            }
                        </div>
                    </div>
                </div>

                <div class="col-md-4 col-lg-4">
                    <div class="card">
                        <h5 class="card-title"><strong>En Yeni Mesajlar</strong></h5>
                        <div class="media-list media-list-hover media-list-divided">
                            @foreach (var item in Model.Mesajlar)
                            {
                                <div class="media">
                                    <img class="avatar" src="img/chat.png">
                                    <div class="media-body">
                                        <p><strong>@item.Kullanici</strong> <time class="float-right" datetime="2017-07-14 20:00">@item.Tarih</time></p>
                                        <p>@item.Mesaj</p>
                                        <p><strong>@item.Baslik</strong></p>
                                        <div class="media-block-actions">
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>




            </div>
        </div><!--/.main-content -->
        <!-- Footer -->
        <footer class="site-footer">
            <div class="row">
                <div class="col-md-6">
                    <p class="text-center text-md-left">Tüm Hakları Saklıdır © 2019.</p>
                </div>
                <div class="col-md-6">
                    <ul class="nav nav-primary nav-dotted nav-dot-separated justify-content-center justify-content-md-end">
                        <li class="nav-item">
                            <a class="nav-link" href="">Hakkımızda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="">İletişim</a>
                        </li>
                    </ul>
                </div>
            </div>
        </footer>
        <!-- END Footer -->
    </main>
    <!-- END Main container -->
    <!-- Global quickview -->
    <!-- END Global quickview -->
    <!-- Scripts -->
    <script src="js/core.min.js"></script>
    <script src="js/app.min.js"></script>
</body>
</html>

WebApplication1/WebApplication1/Views/Home/İletisim.cshtml
@model WebApplication1.Models.IletisimModel

@{
    ViewBag.Title = "Login";
}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Responsive admin dashboard and web application ui kit. ">
    <meta name="keywords" content="login, signin">
    <title>Login Page 1 &mdash; TheAdmin</title>
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,300i" rel="stylesheet">
    <!-- Styles -->
    <link href="~/css/core.min.css" rel="stylesheet">
    <link href="~/css/app.min.css" rel="stylesheet">
    <link href="~/css/style.min.css" rel="stylesheet">
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="~/img/apple-touch-icon.png">
    <link rel="icon" href="~/img/favicon.png">
</head>
<body style="background: url(../img/wallpaper.jpg) no-repeat center center fixed; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;">
    <div class="row min-h-fullscreen center-vh p-20 m-0">
        <div class="col-12">
            <div class="card card-shadowed px-50 py-30 w-400px mx-auto" style="max-width: 100%">
                <h5 class="text-uppercase">İletişim</h5>
                <br>
                <form class="form-type-material" method="post" action="@Url.Action("Iletisim","Home")">
                    <div class="form-group">
                        @Html.TextBoxFor(model => model.Eposta, new { @class = "form-control"})
                        <label for="username">E-Posta Adresi</label>
                    </div>
                    <div class="form-group">
                        @Html.PasswordFor(model => model.Sifre, new { @class = "form-control"})
                        <label for="password">Şifre</label>
                    </div>
                    <div class="form-group flexbox flex-column flex-md-row">
                        <a class="text-muted hover-primary fs-13 mt-2 mt-md-0" href="@Url.Action("ForgottenPassword","Account")">Şifreni mi Unuttun?</a>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-bold btn-block btn-primary" type="submit">Giriş Yap</button>
                    </div>
                    @if(String.IsNullOrEmpty(Model.Error))
                    {

                    }
                    else
                    {
                        <center><span style="color:red;">@Model.Error</span></center>
                    }
                </form>
                <p class="text-center text-muted fs-13 mt-20">Hesabın yok mu? <a class="text-primary fw-500" href="@Url.Action("Register","Account")">Kayıt Ol</a></p>
            </div>
        </div>
    </div>


    <!-- Scripts -->
    <script src="~/js/core.min.js"></script>
    <script src="~/js/app.min.js"></script>
</body>
</html>